spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx3dc691f793a2ca1c
  mpAppSecret: 1cd44ad33a96db45a5cfec585e10926f
  mchId: 1514671951
  mchKey: kevinismydogkiwiismydaughter1234
  keyPath: /Users/nestmilk/Documents/sell_java/h5.p12
  notifyUrl: http://pombase.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: lb6JEX85jdfPVojlozD1wW05pU4FUQNJBdrmmoZG9Yk

logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
